name: Unpublished Tags
description: Compare Docker registry and GitHub repository to get unpublished tags

inputs:
  dockerhub-repository:
    description: Docker repository to fetch latest tag from
    required: true
  first-tag:
    description: First tag to publish – useful when e.g. the project was not dockerized before
    required: false
  checkout-path:
    description: Path in which checkout was committed
    required: false
    default: .
outputs:
  unpublished:
    description: Tags that are in the git repository but not published on Docker Hub yet
    value: ${{ steps.tags.outputs.unpublished }}
  published:
    description: Tags that are already published on Docker Hub
    value: ${{ steps.tags.outputs.published }}

runs:
  using: composite
  steps:
    - name: Get last published version
      id: latest
      shell: bash
      env:
        DOCKERHUB_REPOSITORY: ${{ inputs.dockerhub-repository }}
      run: ${{ github.action_path }}/src/get_last_published_version
    - name: Get all tags since last publish
      id: tags
      env:
        LAST_PUBLISHED_REF: ${{ steps.latest.outputs.tag }}
        FIRST_TAG: ${{ inputs.first-tag }}
        WORKDIR: ${{ inputs.checkout-path }}
      shell: bash
      run: ${{ github.action_path }}/src/get_all_tags_since_last_publish
